### ISSUE TITLE
Print definitions in v0.10.0 is broken

### ISSUE THREAD

**Issue by eloo** [cucumber/godog#340]
### What version of godog are you using?
```
Godog version is: v0.10.0
```

### What version of Go are you using?
```
go version go1.15 darwin/amd64
```

### What did you do?
Running `godog -d` with a code snippet like this
```
 package main

import (
	"github.com/cucumber/godog"
	"log"
)

func InitializeTestSuite(ctx *godog.TestSuiteContext) {
	log.Println("InitializeTestSuite")
	ctx.BeforeSuite(func() {
		log.Println("BeforeSuite")
	})
}

func InitializeScenario(ctx *godog.ScenarioContext) {
	log.Println("InitializeScenario")
	ctx.BeforeScenario(func(*godog.Scenario) {
		log.Println("BeforeScenario")
	})

}
```

### What did you expect to see?
I expect to see my definition.
In this case no definition should printed. 
But also with a step defined you will get an error.

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x142aad6]

goroutine 1 [running]:
github.com/cucumber/godog.runWithOptions(0x14fe9f2, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15219b0, 0x15219b8, ...)
        .../golang/pkg/mod/github.com/cucumber/godog@v0.10.0/run.go:275 +0xa36
github.com/cucumber/godog.TestSuite.Run(0x14fe9f2, 0x4, 0x15219b0, 0x15219b8, 0xc0001d1260, 0xc000100058)
        .../golang/pkg/mod/github.com/cucumber/godog@v0.10.0/run.go:445 +0x158
main.main()
        /var/folders/pr/hy7hjd_j6ll8xy9h0147snhw000107/T/go-build079237889/b001/_testmain.go:30 +0x65
```

### Notes
I've tested the -d command also with the v0.9.0 syntax and this is working.
Looks like the -d command has not been ported to v0.10.0 already.

Thanks

**Comment by lonnblad** [comment]
Hej @eloo, thanks for reporting!

BR Fredrik

**Comment by lonnblad** [comment]
I believe this was an issue with some deprecated code, which is now removed and when using the master version, `godog -d` now works.
